name: generate arcade contribution graphs

on:
  schedule:
    - cron: '0 */12 * * *'

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # PACMAN
      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: 'pacman'

      # save pacman files temporarily
      - name: Save Pacman Files
        run: |
          mkdir -p temp/pacman
          cp -r dist/* temp/pacman/

      # GALAGA
      - name: Generate Galaga Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: 'galaga'

      # merge both outputs
      - name: Merge SVG Files
        run: |
          cp -r temp/pacman/* dist/

      # deploy once
      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
